apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment
  labels:
    app: reactapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
      - name: reactapp
        image: 519852036875.dkr.ecr.us-east-2.amazonaws.com/reactapp:latest
        ports:
        - containerPort: 3000

----
apiVersion: v1
kind: Service
metadata:
  labels:
    name: reactapp
  name: reactapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    name: reactapp
