
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment
  labels:
    app: reactapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
      - name: nodeapp
        image: 519852036875.dkr.ecr.us-east-2.amazonaws.com/my-node.js-app:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: reactapp-service
spec:
  selector:
    app: reactapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
